title: Mario De Frutos Díeguez (Chief Trolling Officer)
description: This is the personal site of Mario De Frutos Díeguez, AKA, Ethervoid. 

google_analytics: UA-44617549-2

theme: jekyll-theme-merlot

plugins:
 - jekyll-sitemap
